/*
  glossary.js — plain-language tooltips for SULFUR stats.
  Condensed from _sulfur_extract/PARAMETER_GLOSSARY.md (the code-traced "how the game leverages
  each parameter" reference). window.SULFUR_GLOSSARY.attr is keyed by backend attribute tag;
  .derived is keyed by the calculator's own derived display labels. app.js `tip()` reads both.
*/
(function () {
  window.SULFUR_GLOSSARY = {
    // --- calculator-derived weapon stats (keyed by display label) ---
    derived: {
      "Damage / shot": "Total damage of one shot (per-pellet damage × pellets), before crit and resistance.",
      "Pellets": "Projectiles fired per shot — shotguns fire several; set by the caliber.",
      "Fire rate": "Shots per second (RPM ÷ 60).",
      "Magazine": "Rounds per reload.",
      "Reload": "Seconds to reload.",
      "Bullet speed": "How fast the projectile travels.",
      "Spread": "Bullet bloom cone in degrees (0–100). Lower is more accurate.",
      "Recoil": "Camera kick per shot (the caliber's kick power × KickMultiplier). Lower is steadier.",
      "Durability": "The weapon's durability pool; at 0 it breaks and loses its bonuses until repaired.",
      "Durability / shot": "Durability spent per shot: 1 by default, +1 per enchantment (unless it says it doesn't add, or costs more).",
      "Shots to break": "How many shots the weapon can fire before it breaks (durability ÷ per-shot cost).",
      "Crit (ADS)": "Extra critical-hit chance while aiming down sights.",
      "Full-auto": "Whether the weapon fires fully automatically.",
    },
    // --- backend attribute tags ---
    attr: {
      // weapon core / handling (ItemAttributes)
      Damage: "The weapon's per-projectile base damage.",
      RPM: "Rounds per minute (fire rate).",
      Spread: "Bullet spread/bloom cone in degrees (0–100). Lower is more accurate.",
      KickMultiplier: "Scales this weapon's recoil kick (base 1.0). Lower is steadier.",
      ReloadSpeed: "Modifies reload time.",
      CritChance: "The weapon's own crit chance, added to yours. Crit is a flat ×2 on hit.",
      CritChanceADS: "Extra crit chance only while aiming down sights.",
      FullAuto: "Weapon fires fully automatically (also enables the full-auto damage bonus).",
      Silenced: "Suppressed — no AI alert and quieter fire.",
      DisableADS: "Weapon cannot aim down sights.",
      DisableMuzzleFlash: "Suppresses the muzzle-flash visual.",
      MaxDurability: "The item's maximum durability.",
      DurabilityLoss: "Multiplier on how fast durability is spent per shot.",
      Durability: "Current durability (condition).",
      Experience: "The weapon's accumulated XP, which drives rank-ups.",
      ConsumeAmmoChance: "Chance a shot spends ammo (below 1 = chance of a free shot).",
      ConsumeExtraAmmoChance: "Chance a shot burns one extra round.",
      AimMovingBonus: "Reduces the accuracy penalty for firing while moving.",
      KnockbackPower: "Knockback force applied on hit.",
      // projectile flight (ItemAttributes.Projectile*)
      ProjectileAmount: "Pellets/projectiles fired per shot.",
      ProjectilePenetration: "How many enemies/surfaces a bullet passes through.",
      ProjectilePenetrationDamageMultiplier: "Damage retained after each pierce.",
      ProjectileBounce: "How many times bullets bounce off geometry.",
      ProjectileBounciness: "Velocity retained per bounce.",
      ProjectileMass: "Bullet drop — heavier means more gravity.",
      ProjectileScale: "Bullet size (also scales AoE and beams).",
      ProjectileTimeScale: "Bullet speed multiplier.",
      ProjectileGravityFactor: "Gravity multiplier on the bullet.",
      ProjectileDrag: "Air drag — the bullet slows over distance.",
      ProjectileForce: "Extra launch impulse (higher muzzle velocity).",
      ProjectileLifeTime: "How long a bullet lives, in seconds.",
      ProjectileMoveAsLight: "Hitscan — instant, beam-like travel (not player move speed).",
      ProjectileMoveAsSpray: "Sprays projectiles in a wide cone.",
      ProjectileBeam: "Fires a continuous beam.",
      ProjectileKinematicForce: "Turns bullets into physics rocket-style projectiles.",
      Homing: "Bullets home toward the nearest on-screen enemy.",
      ProjectileTurnOffBulletHoles: "Cosmetic — no bullet-hole decals.",
      DisableBloodOnHit: "Cosmetic — no blood on hit.",
      ShootEffectSoundOnly: "Plays only the shot sound, skipping the visual.",
      ImpactEffectSoundOnly: "Plays only the impact sound, skipping the visual.",
      // on-hit status your bullets apply
      ProjectileApplyFire: "Bullets set the target on fire (Burning DoT), +100% proc.",
      ProjectileApplyFrost: "Bullets freeze the target; a full freeze can shatter/instakill.",
      ProjectileApplyElectricity: "Bullets electrocute (worse if the target is Wet).",
      ProjectileApplyPoison: "Bullets poison the target (~25% proc).",
      ProjectileApplyStun: "Bullets stun the target (~20% proc).",
      ProjectileApplyBlind: "Bullets blind the target (~5% proc).",
      ProjectileApplyCharm: "Bullets charm the target to fight for you.",
      ProjectileApplyCrusader: "Each hit marks the target to reflect Holy damage.",
      ProjectileApplyFear: "Bullets make the target flee.",
      ProjectileApplyOil: "Coats the target in oil (amplifies Fire, slows).",
      ProjectileApplyPetrification: "Bullets turn the target to stone.",
      ProjectileApplyRoot: "Bullets root the target in place.",
      ProjectileApplyVoodoo: "Links targets so damage is shared between them.",
      ProjectileApplyWet: "Soaks the target (amplifies Electric).",
      ProjectileOnHitNoxiosaCloud: "Spawns a poison cloud on hit.",
      ProjectileOnHitAftershock: "Impact shocks nearby enemies (AoE).",
      ProjectileOnHitStormSurge: "Electric discharge AoE on hit.",
      ProjectileOnHitExplosionRPG: "Bullets become rockets that explode.",
      ProjectileOnHitLava: "Leaves burning lava on hit.",
      ProjectileOnHitWater: "Douses the target (applies Wet).",
      ProjectileOnHitOil: "Drenches the target in oil.",
      ProjectileHolyWater: "Holy-water effect on hit.",
      ProjectilePollen: "Target sneezes poison and flees (spreads).",
      ProjectileCryoSnakes: "Chance to spawn cryo snakes on impact.",
      ProjectilePrism: "Each shot picks a random element.",
      ProjectileVinesprout: "Roots the target and grows vines.",
      ProjectileMetamorph: "Chance to gib an enemy into an item or new enemy.",
      // enchant mechanics
      EnchantmentDurabilityCost: "Per-shot durability cost this enchant adds.",
      EnchantmentIncreaseHeadshotDamage: "Multiplies headshot damage.",
      EnchantmentSelfDamage: "Firing hurts you.",
      EnchantmentDamageAoe: "Deals AoE damage around you when firing.",
      EnchantmentRemoveBullets: "Fires no bullets — a pure-effect weapon.",
      // dual-wield / conditional weapon damage
      ExtraDamage_RightGun: "Bonus damage from the right barrel (dual-wield).",
      ExtraDamage_LeftGun: "Bonus damage from the left barrel (dual-wield).",
      ExtraDamageGhost: "Bonus damage against Ghost-type enemies.",
      ItemStat_JumpPower: "Bonus jump height while this weapon is held.",
      ItemStat_MoveSpeed: "Move-speed multiplier while this weapon is held.",
      ItemStat_LootChanceMultiplier: "Improves loot-roll odds while held.",
      DisableLootMoney: "Kills by this weapon drop no money.",
      DisableLootOrgans: "Kills by this weapon drop no organs.",
      // --- worn gear: player stats (EntityAttributes) ---
      Resistance_Armor: "Armor: % reduction vs plain bullet/melee (Normal) damage. This is the defensive stat, NOT gear durability.",
      Resistance_Fire: "Reduces Fire damage and Burning ticks (0–100%; 100 = immune).",
      Resistance_Frost: "Reduces Frost (and Water) damage (0–100%).",
      Resistance_Electric: "Reduces Electric damage and Electrocuted ticks (0–100%).",
      Resistance_Poison: "Reduces Poison damage and Poisoned ticks (0–100%).",
      Resistance_Explosive: "Reduces Explosive damage (on top of the flat ×0.2 player cut).",
      Resistance_Holy: "Reduces Holy damage (0–100%).",
      Resistance_Charm: "Reduces the chance of being Charmed.",
      Resistance_Earth: "Crowd-control resist bucket (Blind/Entangle/Oily/Root/Stun/Wet) — misnamed; there's no Earth damage.",
      Resistance_Bleed: "Reduces Bleed (and Sacrifice) damage.",
      Resistance_Petrified: "Reduces the chance of being Petrified.",
      Resistance_Punish: "The only way to reduce Punish — a 'true' damage that bypasses the usual player ×0.5.",
      ExtraDamage_Melee: "Bonus damage to your melee weapons.",
      ExtraDamage_Pistol: "Bonus damage to your pistols.",
      ExtraDamage_Revolver: "Bonus damage to your revolvers.",
      ExtraDamage_Automatic: "Bonus damage while a weapon is firing full-auto.",
      ExtraDamage_Rifle: "Bonus damage to your rifles.",
      ExtraDamage_Shotgun: "Bonus damage to your shotguns.",
      ExtraDamage_Sniper: "Bonus damage to your sniper rifles.",
      ExtraDamage_SMG: "Bonus damage to your SMGs.",
      ExtraDamage_LMG: "Bonus damage to your LMGs.",
      Stat_MeleeDamage: "An enemy's melee-attack damage — NOT yours (player melee uses melee-weapon bonuses).",
      Stat_GlobalDamageMultiplier: "Multiplies ALL your outgoing weapon damage.",
      Stat_CritChance: "Your base chance to land a critical hit (flat ×2 damage).",
      Stat_CritChanceADS: "Extra crit chance while aiming down sights.",
      Stat_MaxHealth: "Your maximum health.",
      Stat_HealthRegen: "How fast your health regenerates (HP/second).",
      Stat_Lifesteal: "Heals you for a percent of the damage you deal.",
      Stat_Thorns: "Reflects a fraction of melee damage back at the attacker.",
      Stat_MovementSpeed: "Overall run/walk speed multiplier.",
      Stat_SprintBonus: "How much faster sprinting makes you.",
      Stat_Charisma: "Haggling — up to 50% off vendor prices at 100 (outside safe zones).",
      Stat_AimMovingBonus: "Reduces the accuracy penalty for firing while moving.",
      Stat_ExtraJumps: "Extra mid-air jumps (double/triple jump).",
      Stat_JumpPower: "Jump height / launch force.",
      Stat_SwimSpeed: "Underwater swim speed.",
      Stat_CoyoteTime: "Grace window (seconds) to still jump just after walking off a ledge.",
      Stat_CrouchSlide: "Enables the crouch-slide move (sprint + crouch).",
      Stat_SpringyShoes: "Cosmetic — changes the jump sound only.",
      Stat_Blindfolded: "Screen goes fully black; grants flashbang immunity.",
      Stat_WearingShades: "Slight screen dim; grants flashbang immunity.",
      Stat_WearingEarPro: "Muffles loud/flash audio (does not block the visual flash).",
      Stat_WearingRudolfNose: "Cosmetic glowing-red nose effect.",
      Stat_LungCapacity: "How long you can hold your breath underwater.",
      Stat_LuckGain: "Passive Luck buildup over time (feeds loot luck).",
      Stat_WeaponWeightPenalty: "How much of a heavy weapon's slowdown applies (0 = ignore weight, 1 = full penalty).",
      Status_WearingGoggles: "Clear underwater vision (removes the depth blur).",
      Status_WearingStraitJacket: "Weapons and inventory are locked; struggle to escape.",
    },
  };
})();
